name: Deploy MlFlow to Server

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create dynamic google_sa.json file
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "google_sa.json"
          json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          dir: "mlflow/"
      - name: Run setup script
        run: |
          if [ -f /home/ubuntu/mlflow/docker-compose.yaml ]
          then
              echo "yes"
              docker-compose -f /home/ubuntu/mlflow/docker-compose.yaml down
              rm -rf /home/ubuntu/mlflow
              mkdir /home/ubuntu/mlflow
              cp -r mlflow/* /home/ubuntu/mlflow
          else
              echo "no"
              mkdir -p /home/ubuntu/mlflow
              cp -r mlflow/* /home/ubuntu/mlflow
          fi
      - name: Populate .env file
        run: |
          touch /home/ubuntu/mlflow/.env
          echo "${{ secrets.MLFLOW_ENV }}" > /home/ubuntu/mlflow/.env
          cat /home/ubuntu/mlflow/.env
      - name: Docker Compose Up for MlFlow
        run: |
          sudo docker-compose -f /home/ubuntu/mlflow/docker-compose.yml up --build -d
      - name: Check MlFlow heartbeat
        run: |
          RESPONSE=$(curl -s http://${{ secrets.HOST }}:7070/health)
          echo "MLflow Health Check Response: $RESPONSE"
          if echo "$RESPONSE" | grep -q '"status": "OK"'; then
            echo "✅ MLflow is healthy"
          else
            echo "❌ MLflow health check failed"
            exit 1
          fi
      - name: Success
        run: echo "✅ Vector DB deployed successfully!"