name: Deploy Vector Database to Server

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Airflow heartbeat
        run: |
          RESPONSE=$(curl -s http://${{ secrets.HOST }}:8080/health)
          echo "Airflow Response: $RESPONSE"
          
          SCHEDULER_HEALTH=$(echo "$RESPONSE" | jq -r '.scheduler.status')
          TRIGGERER_HEALTH=$(echo "$RESPONSE" | jq -r '.triggerer.status')
          
          if [[ "$SCHEDULER_HEALTH" == "healthy" && "$TRIGGERER_HEALTH" == "healthy" ]]; then
            echo "✅ Airflow scheduler and triggerer are healthy"
          else
            echo "❌ Airflow health check failed"
            exit 1
          fi
      - name: Run setup script
        run: |
          if [ -f $HOME/vector-database/docker-compose.yml ]
          then
              echo "yes"
              docker-compose -f $HOME/vector-database/docker-compose.yml down
              rm -rf $HOME/vector-database/docker-compose.yml
              cp -r vector_db/docker-compose.yml $HOME/vector-database/docker-compose.yml
          else
              echo "no"
              mkdir -p $HOME/vector-database
              cp -r vector_db/docker-compose.yml $HOME/vector-database/docker-compose.yml
          fi
      - name: Docker Compose Up for Vector DB
        run: |
          docker-compose -f $HOME/vector-database/docker-compose.yml up --build -d
      - name: Check Vector DB heartbeat
        run: |
          sleep 30
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.HOST }}:8000/api/v2/heartbeat)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "❌ ChromaDB heartbeat check failed. HTTP $RESPONSE"
            exit 1
          else
            echo "✅ ChromaDB heartbeat OK. HTTP $RESPONSE"
          fi
      - name: Success
        run: echo "✅ Vector DB deployed successfully!"