name: Deploy Vector Database to Server

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Airflow heartbeat
        run: |
          RESPONSE=$(curl -s http://${{ secrets.HOST }}:8080/health)
          echo "Airflow Response: $RESPONSE"
          
          SCHEDULER_HEALTH=$(echo "$RESPONSE" | jq -r '.scheduler.status')
          TRIGGERER_HEALTH=$(echo "$RESPONSE" | jq -r '.triggerer.status')
          
          if [[ "$SCHEDULER_HEALTH" == "healthy" && "$TRIGGERER_HEALTH" == "healthy" ]]; then
            echo "✅ Airflow scheduler and triggerer are healthy"
          else
            echo "❌ Airflow health check failed"
            exit 1
          fi
      - name: Change the mode of the setup script
        run: sudo chmod +x ./vector_db/setup.sh
      - name: Run setup script
        run: sudo ./vector_db/setup.sh
      - name: Check Vector DB heartbeat
        run: |
          RESPONSE=$(curl -s http://${{ secrets.HOST }}:8000/api/v2/heartbeat)
          echo "Vector DB Response: $RESPONSE"
          if echo "$RESPONSE" | grep -q '"nanosecond heartbeat"'; then
            echo "✅ Vector DB is healthy"
          else
            echo "❌ Vector DB health check failed"
            exit 1
          fi
      - name: Success
        run: echo "✅ Vector DB deployed successfully!"